---
name: build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v22
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: build AutoHyperlinks
        working-directory: Auto-Hyperlinks
        run: |
          xcodebuild \
            -target AutoHyperlinks.framework \
            -configuration Release \
            build
      - name: build nvalt
        run: |
          nix build .#deps
          xcodebuild \
            -target Notation \
            -configuration ForBuilding \
            -scheme 'Notation Release' \
            -archivePath ./nvalt.xcarchive \
            archive
          ditto -c -k --keepParent nvalt.xcarchive/Products/Applications/nvALT.app nvALT.zip
      - uses: actions/upload-artifact@v7
        with:
          name: nvALT
          path: nvALT.zip
      - name: release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v3
        with:
          files: |
            nvALT.zip
